modLoader="javafml"
loaderVersion="[47,)"
license="GNU AGPLv3"

[[mods]]
modId="dimstorage"
version="${mod_version}"
displayName="DimStorage"
updateJSONURL="https://api.modrinth.com/updates/dimstorage/forge_updates.json"
issueTrackerURL="https://github.com/Edivad99/DimStorage/issues"
modUrl="https://www.curseforge.com/minecraft/mc-mods/dimstorage"
credits="I would like to thank Thegaarnik for giving me the opportunity to publish and update this mod."
authors="Edivad99"
description="DimStorage add a technologic version of ender chest system with owner, frequence selection and lock system."

[[dependencies.dimstorage]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.dimstorage]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="BOTH"
[[dependencies.dimstorage]]
    modId="edivadlib"
    mandatory=true
    versionRange="[2.0.1,)"
    ordering="NONE"
    side="BOTH"
